{% set name = "flask-limiter" %}
{% set version = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flask_limiter-{{ version }}.tar.gz
  sha256: f9e3e3d0c4acd0d1ffbfa729e17198dd1042f4d23c130ae160044fc930e21300

build:
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - limits >=3.13
    - flask >=2
    - ordered-set >4,<5
    - rich >=12,<14

test:
  imports:
    - flask_limiter
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://flask-limiter.readthedocs.org
  summary: Rate limiting for flask applications
  description: |
    Flask-Limiter adds rate limiting to Flask applications.
    By adding the extension to your flask application, you can configure various rate limits at different levels (e.g. application wide, per Blueprint, routes, resource etc).
  dev_url: https://github.com/alisaifee/flask-limiter
  doc_url: https://flask-limiter.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
