{% set name = "flask-limiter" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-Limiter-{{ version }}.tar.gz
  sha256: 919b4af05b7d4162a699bfdc24357feeec876b70b1916150c3b4337ad711a995

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - limits >=2.8
    - flask >=2
    - ordered-set >4,<5
    - rich >=12,<14
    - typing-extensions >=4

test:
  imports:
    - flask_limiter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://flask-limiter.readthedocs.org
  summary: Rate limiting for flask applications
  dev_url: https://github.com/alisaifee/flask-limiter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
